### PR TITLE
A few cipher implementations for #150

### PR DESCRIPTION
**Pull request by hargoniX**
#### Short description of what this resolves:
#150 But not completely, i left several ciphers out in case somebody else, for example @V1NAY8, wants to implement them
#### Changes proposed in this pull request:
- Adding a new command to the dev module called cipher which has two subcommands, encrypt and decrypt
- A small class based system around ciphers in dev.py so people can add them more easily
- The Atbash, Caesar and the ROT13 Cipher using the mentioned class based system

**Fixes**: #150 But again, not completely.

In case you want me to implement all of the ciphers mentioned in the issue, I would happily do that, too.

### CODE REVIEW

**Comment by hargoniX** [comment]
I am not exactly sure wether this is my fault as Travis appears to have a problem with unittests which are not related to my feature.

**Comment by manparvesh** [comment]
@hargoniX I think the tests are failing because the code you are on doesn't have the latest changes. You could [sync your forked repo](https://help.github.com/articles/syncing-a-fork/) and manage the merge conflicts.

**Comment by V1NAY8** [comment]
Implementation looks good instead I wanted to create a folder in modules for cipher and have a base.py and then each file for one cipher it would look more structured.

**Comment by hargoniX** [comment]
@manparvesh Ok currently on it

@V1NAY8 I thought about that at first but the issue clearly said module:dev so i put the stuff in the dev module.

**Comment by manparvesh** [comment]
@hargoniX I agree with @V1NAY8 
One cipher per file would be more structured and maintainable.

**Comment by V1NAY8** [comment]
Let's wait for unit tests to complete on @hargoniX  code
I say create a cipher folder 
we create a base.py for basic modules which are common for all
a new file for each implementation
ill make a pr

**Comment by hargoniX** [comment]
All classes just need to have an encrypt and a decrypt argument taking one parameter which is the message. As every cipher reimplements these methods it is not useful to have a base class for it.

**Comment by V1NAY8** [comment]
Yeah correct almost forgot that

**Comment by manparvesh** [comment]
@hargoniX can you please add some tests to cover the code you've written?
Also, please update the README to with some sample outputs and usage

**Comment by hargoniX** [comment]
I've rarely implement unit tests before so this might be a dumb question. 
As all the ciphers i have implemented require input from stdin via the `input` function I am not exactly sure how to implement unittests for them. Any suggestions are appreciated.

**Comment by manparvesh** [comment]
@hargoniX @V1NAY8 you can take a look inside the `tests` directory to get an idea of how you can write tests for commands in `yoda`

**Comment by V1NAY8** [comment]
@manparvesh I ran the tests on ciphers @hargoniX  has written..
They are working..
How do i update the readme file because I can't operate on this pull request..

**Comment by hargoniX** [comment]
Have you put the tests somewhere on GitHub? @V1NAY8

**Comment by V1NAY8** [comment]
@hargoniX 
I have the screenshots and i should write a test file for it .... for the tests folder

**Comment by hargoniX** [comment]
Well I asked him wether he put the stuff on GitHub somewhere so I could take a look at it, I didn't really understand his response to that question as I was asking for some source code for the tests he wrote so I thought maybe he'll send it later and now we are here.

**Comment by manparvesh** [comment]
@hargoniX okay, in case he is not available, we can merge this PR and someone can create another PR for adding tests and anything else that is remaining.

**Pull request merged**
