### PR TITLE
Adds Black

### PR DESCRIPTION
**Pull request by mondaini**
#### Short description of what this resolves: 
Reformatted using black

#### Changes proposed in this pull request:

- Reformatted style using black (default)
- Adds Black Badge to README.md

**Fixes**: #216

### CODE REVIEW

**Comment by mondaini** [comment]
@manparvesh Trying to figure out why I've got 74.95% of diff hit by codecov/patch. I'm running yoda locally  after these linting changes and I haven't got any issues yet.

**Comment by manparvesh** [comment]
@mondaini I think that can be ignored.
Let me know when you are done with your part and remove the Work in progress part from the PR title.

**Comment by mondaini** [comment]
It seems it has a conflict now. I'm not sure which snippet must be added. @manparvesh Can you help me resolving this?

```
<<<<<<< master
        response = subprocess.check_output(
            ["curl", "-F", "file=@" + path, "https://file.io"]
        )

        response_json = json.loads(response)
        if "link" in response_json.keys():
            click.echo(chalk.green("File Link : " + response_json["link"]))
            click.echo(
                chalk.yellow("WARNING: File will be deleted after it is accessed once.")
            )
=======
        files = {'file': open(path, 'rb')}
        resp = requests.post('https://file.io', files=files)
        response_json = json.loads(resp.text)
        if 'link' in response_json.keys():
            click.echo(chalk.green("File Link : " + response_json['link']))
            click.echo(chalk.yellow("WARNING: File will be deleted after it is accessed once."))
>>>>>>> master
```

**Comment by thornycrackers** [comment]
@mondaini I added the bottom snippet in master to use requests instead of calling curl to fix the broken tests.

**Comment by mondaini** [comment]
> @mondaini I added the bottom snippet in master to use requests instead of calling curl to fix the broken tests.

Great. I'm gonna choose the request snippet then. :-)

**Comment by manparvesh** [comment]
@mondaini 
This looks fine to me. I'll merge it ✔️
Thanks a lot for contributing! :smile:

**Pull request merged**
