### PR TITLE
#154 | Implementation of WhoIs search

### LINKED ISSUE #154: whois search
whois information for a domain name, if that is something that can be fetched using some API. I have not explored this.

### PR DESCRIPTION
**Pull request by Khukhuna**
### Closes #154 
- Implementation of **WhoIs** search.  _(Scraping of https://whois.com website)_

Example:

### CODE REVIEW

**Comment by Khukhuna** [comment]
P.S. Im not native english speaker, so if there is any grammatical error please let me know :smile:

**Comment by Khukhuna** [comment]
@manparvesh  Done :tada:

**Comment by Khukhuna** [comment]
@manparvesh Done :tada:

**Comment by Khukhuna** [comment]
@manparvesh Done :tada: :smiley:

**Comment by Khukhuna** [comment]
Just found out that codecov checks are failing... Any idea why? I've never worked with codecov before.

**Comment by manparvesh** [comment]
@Khukhuna 
This looks fine to me. I'll merge it ✔
Thanks a lot for contributing! :smile:️

**Pull request merged**
