### PR TITLE
Fix python 3 build

### PR DESCRIPTION
**Pull request by tirkarthi**
#### Changes proposed in this pull request:

- Fixes Python 3 build failure
- Cache pip dependencies in Travis

### CODE REVIEW

**Comment by tirkarthi** [comment]
Python 2 build fails because the external service used is little falky. One possible solution will be to use mocked responses instead of depending on the external service. I am not doing this as part of this PR. Feel free to open a separate issue to track this.

Thanks

**Comment by manparvesh** [comment]
@tirkarthi the python 3 build is fixed but it seems that python 2 build is failing now :sweat_smile:

**Comment by tirkarthi** [comment]
@manparvesh  Please try re-running the build. As I mentioned in the above comment it's due to a flaky test that depends upon an external service.

Ref : https://travis-ci.org/yoda-pa/yoda/jobs/382537316#L584
Successful build : https://travis-ci.org/tirkarthi/yoda/builds/382536166

**Comment by manparvesh** [comment]
@tirkarthi I restarted the build and it was successful! I'll merge this. 
Thanks for contributing! :smile:

**Pull request merged**
