### PR TITLE
Added hacker news- dev tools

### PR DESCRIPTION
**Pull request by skcse**
#### Short description of what this resolves:
I Have added Hacker-news in dev.py
#### Changes proposed in this pull request:
I have used newsapi.org (https://newsapi.org/s/hacker-news-api) for adding hacker-news

### CODE REVIEW

**Comment by manparvesh** [comment]
@skcse thanks for taking the time to contribute!
Could you also please add a screenshot of a sample output for this command? I will be really helpful.
Thanks

**Comment by skcse** [comment]
@manparvesh My pleasure!
Screenshot is attached
yoda3
yoda2
yoda1

**Comment by skcse** [comment]
@manparvesh 
I have modified all command of "chalk" as mentioned in a comment in [issues 79](https://github.com/yoda-pa/yoda/issues/79)

**Comment by manparvesh** [comment]
@skcse this is great!
Thank you so much for contributing!
Also, since you still seem like a student, just a note for your future contributions (not just for this project but for your future jobs too): please keep different pull requests for different tasks, it helps a lot in tracking issues.
Thanks again. I'm merging this

**Comment by skcse** [comment]
@manparvesh Thank you for the note 
I will follow it from next time

**Pull request merged**
