### PR TITLE
adding sms feature, and python-dbus dependency

### PR DESCRIPTION
**Pull request by skymoore**
#### Short description of what this resolves:
Adds the ability for yoda to use your kdeconnect connected smart phone to send an sms to a friend registered in the people config file.
#### Changes proposed in this pull request:
+add people sms feature
+add python-dbus dependency

### CODE REVIEW

**Comment by mskymoore** [comment]
image
check fails with:
```
File "/home/travis/build/yoda-pa/yoda/modules/people.py", line 7, in <module>
    import dbus
ModuleNotFoundError: No module named 'dbus'
```
Obviously python-dbus and python3-dbus are valid packages that can be used by importing them with
```
import dbus
```
as can be seen by my screenshot, or by installing the package/s on your distro and running my code.  Must be a travis issue?  Any input on how to get this to pass would be great.

**Comment by manparvesh** [comment]
@mskymoore sorry for late reply.
Regarding `dbus`, can you try adding `libdbus-glib-1-dev` to the installation script? Taken from [this comment](https://github.com/willprice/python-omxplayer-wrapper/issues/115#issuecomment-350405653).
I found no solid fix regarding this on the internet either.

**Comment by skymoore** [comment]
@manparvesh did this repo get unarchived?

**Comment by manparvesh** [comment]
@skymoore yes I unarchived it a few days ago.

**Comment by skymoore** [comment]
> @skymoore yes I unarchived it a few days ago.

@manparvesh What's the plan?

**Pull request closed without merging**
