### PR TITLE
Issue 76 remove stacktrace on invalid expense

### PR DESCRIPTION
**Pull request by WCollins3**
#### Short description of what this resolves:
Invalid expenses are no longer recorded

#### Changes proposed in this pull request:
-none

**Fixes**: #76

### CODE REVIEW

**Comment by manparvesh** [comment]
@WCollins3 this looks good to me. I'll merge this. Thanks

**Comment by WCollins3** [comment]
With the build that failed, it looks like it stopped when uploading to an S3 bucket. If that's the case, is it just a dropped connection that caused this to fail, rather than an issue with the code?

**Comment by manparvesh** [comment]
@WCollins3 yeah, I think we can ignore that failure

**Comment by manparvesh** [comment]
@WCollins3 I reran the build and this time it was successful. It was probably a temporary issue. I'm merging this now

**Pull request merged**
