### PR TITLE
Keyboard shortcuts

### PR DESCRIPTION
**Pull request by c-shekhar**
#### Short description of what this resolves:
Adds Key Bindings Addition(import) and Search feature to dev module.

#### Changes proposed in this pull request:

- AddKeybindings
- SearchKeybindings
- Tests  

**Fixes**: #60

### CODE REVIEW

**Comment by c-shekhar** [comment]
@manparvesh, please review PR for keybindings add and search feature.
Given correct absolute path key bindings can be imported.
Search functionality works as usual with partial matching.
Please Review and let me know, if there are further changes.

**Comment by c-shekhar** [comment]
@manparvesh, @csaranbalaji Please resolve above conflict as I am unable to do so not sure why, Looks some inconsistency due to github migrations.
Rest README, i have updated.

**Comment by c-shekhar** [comment]
@manparvesh, from my end this is Merge Ready.
Please review and let me know if there are any further changes.

**Comment by manparvesh** [comment]
@c-shekhar it seems okay now. 
This looks fine to me. I'll merge it ✔️
Thanks a lot for contributing! :smile:

**Pull request merged**
