### PR TITLE
ascii image transformer script in modules/ folder added

### PR DESCRIPTION
**Pull request by DragonGhost7**
#### Short description of what this resolves:
added ascii-transform command, which transforms an image into ASCII text

### CODE REVIEW

**Comment by DragonGhost7** [comment]
Ok i see the problem

**Comment by DragonGhost7** [comment]
DONE

**Comment by manparvesh** [comment]
@DragonGhost7 great job!
Can you also please update the readme with sample usage and output of this command? Other changes seem fine.

**Comment by manparvesh** [comment]
@DragonGhost7 
This looks fine to me. I'll merge it ✔
Thanks a lot for contributing! :smile:️

**Pull request merged**
