### PR TITLE
Adds more tests.

### PR DESCRIPTION
**Pull request by wastevensv**
#### Short description of what this resolves:
Adding tests for each command in Yoda.
#### Changes proposed in this pull request:

- Adding tests in the test/ directory.

**Fixes**: #16

### CODE REVIEW

**Comment by wastevensv** [comment]
This is still a work in progress. I'm submitting this pull request early to allow for comments on tests while I add them.

**Comment by manparvesh** [comment]
@wastevensv 
Sure, let me know whenever you are done with it.
Thanks for taking out time to contribute!

**Comment by wastevensv** [comment]
Unfortunately, I think this is as much as I will be able to do for the time being. I might try and do more another time.

**Comment by manparvesh** [comment]
@wastevensv I understand. Thank you so much for contributing! :smile:

**Pull request merged**
