### PR TITLE
Add support for custom commands

### LINKED ISSUE #146: Add custom commands
## Description
This is a command to create new commands! 

The user should be able to set a custom command, for example `ls` inside yoda, to call the actual `ls`.
The user would then be able to call this command using `yoda ls`, which would further call the inbuilt `ls` in unix based systems

### PR DESCRIPTION
**Pull request by AlexandruValeanu**
#### Short description of what this resolves:
Adds support for custom commands and closes #146.

#### Changes proposed in this pull request:

- Add new command `cc` to be used for creating custom commands
- Extend `yoda.py` to load/create 'dynamic commands' from a `.json` file of custom commands.

**Fixes**: #146

### CODE REVIEW

**Comment by manparvesh** [comment]
@AlexandruValeanu thanks! Can you also add some information to the README so that one knows how to use this command?

**Comment by AlexandruValeanu** [comment]
@manparvesh Solved (I've also discovered a bug in the process).

**Comment by manparvesh** [comment]
@AlexandruValeanu Can you explain me the bug you found or create an issue for that?

**Comment by AlexandruValeanu** [comment]
@manparvesh Sorry, I should've been clearer. I found a bug with my implementation of custom commands.

**Comment by manparvesh** [comment]
@AlexandruValeanu 

> I found a bug with my implementation of custom commands.

Oh, I understand.

---

On a different note, do you think you could change the implementation a little to something like this:
```
$ yoda cc <name of the custom command> <command to be added>
```
Instead of the current:
```
$ yoda cc <command to be added>
```

I think that simply adding a command to the name you want could possibly cause problems in the case of an existing command.

----

I also have a few questions about the implementation:
1. What happens when one tries to create a command with the name that is already there? For example, trying to add `yoda chat`, but it is already there.
2. In this implementation, can I add a command from their location instead of the preinstalled ones? Something like this:
```
$ yoda cc as /path/to/android-studio
```

**Comment by manparvesh** [comment]
@AlexandruValeanu ?

**Comment by AlexandruValeanu** [comment]
I am still working on it but I couldn't find the time to finish it.

**Comment by manparvesh** [comment]
@AlexandruValeanu Since you didn't get the time to work on it, I resolved the merge conflicts and will merge this for now. If you get time to work on it in the future, I will create an issue for it and you can give it a shot.

Thanks for contibuting!

**Pull request merged**
