### PR TITLE
Added new feature of note with title

### PR DESCRIPTION
**Pull request by Man-Jain**
This contains the enhanced note feature in the diary module which supports notes with a title.
The user when now adds a new note the system will first ask title and then the text for the note.

### CODE REVIEW

**Comment by manparvesh** [comment]
@Man-Jain thanks, This looks good to me.
However, since this has become a big project, please make the following changes as well:
- [ ] Fix tests. Currently due to your change, the tests for diary module are failing,
- [ ] update readme according to the latest changes in the diary module.

**Comment by Man-Jain** [comment]
@manparvesh I have done the changes that you recommended. Please review them.

**Comment by manparvesh** [comment]
@Man-Jain 
This looks fine to me. I'll merge it ✔️
Thanks a lot for contributing! :smile:

**Comment by Man-Jain** [comment]
@manparvesh Thanks for merging. I am looking forward to contribute more.

**Pull request merged**
