### PR TITLE
Git daily summary command

### PR DESCRIPTION
**Pull request by siejqa**
#### Short description of what this resolves:
Created dev command that shows some stats from last 24hr for given user (repos, issues, PRs, commits).
PR submitted for review purposes.
#### Changes proposed in this pull request:

- Created function _gitsummary_ in modules/dev.py
- Added the command dev.gitsummary in yoda.py

**Fixes**: #147

### CODE REVIEW

**Comment by manparvesh** [comment]
@siejqa 
thanks for the implementations, however I would recommend that you create a different test file for each implementation. For the structure, you can look at #25

**Comment by manparvesh** [comment]
@siejqa the code looks fine
 please update the README with a sample output and usage of the command you added

**Comment by siejqa** [comment]
@manparvesh 
Updated the README file.

Question about tests though - without giving away working git credentials I can't test anything else than exiting when user gives wrong credentials. Will it be fine to add mock module to the app to mock the Git API response or just leave it as it is?

**Comment by siejqa** [comment]
@manparvesh No worries, me too :relieved:
I'll try to take care of it in the upcoming days.

**Comment by siejqa** [comment]
@manparvesh 
Recreating the PR as while playing with Github API by mistake I removed my forked yoda. Now I can't change the "from" repository in PR to point to a new fork... :sad:

**Pull request closed without merging**
