### PR TITLE
Include resource files with package.

### PR DESCRIPTION
**Pull request by omaciel**
This fixes issue #28  and it includes the resources files.

### CODE REVIEW

**Comment by omaciel** [comment]
@manparvesh give this a shot when you have a chance?

**Comment by omaciel** [comment]
Travis failed but that is because you don't have any tests :)

**Comment by manparvesh** [comment]
@omaciel sorry #28 was solved by a previous PR, so I can't merge this.

**Comment by manparvesh** [comment]
@omaciel yeah, I figured that out :) Will write tests when I get time. There is also an issue for that (#16). It would be great if you could contribute :)

**Pull request closed without merging**
